### ISSUE TITLE
Doesn't currently work with stable release of ggplot2

### ISSUE THREAD

**Issue by JamieParkinson** [baptiste/gridextra#13]
If one has the current stable release (ie from CRAN) of ggplot2, then attempting to pass a gtable (returned by arrangeGrob) to ggsave gives an error ("plot should be a ggplot2 plot"). Not your problem per se but I guess it could be considered a regression and I thought I'd just let you know.

I imagine this can be fixed by "faking" the class of the gtable but I am not an R developer by any means. Thanks for the useful software!

**Comment by baptiste** [comment]
t works with the dev version of ggplot2, Hadley removed the class test. Unfortunately it may be a little while before it gets to CRAN, in the meantime you could install ggplot2 from github.
