### ISSUE TITLE
Where are the "experimental grobs and functions not widely used" removed in 2.0.0?

### ISSUE THREAD

**Issue by seaaan** [baptiste/gridextra#16]
Hello,
I have some code that uses `borderGrob()` and recently broke when I updated to the new version of `gridExtra`. I see in the NEWS that you removed some experimental grobs and little-used functions in the latest release and the link points me to this repository, but searching doesn't turn anything up. I downgraded to version 0.9.1 to solve my problem, but wanted some clarity about where those functions are available in the repository.
Thanks!
Sean

**Comment by baptiste** [comment]
Sorry about that, but I had to make a selection, it was become a nightmare to maintain this package. [Here's a link](https://github.com/baptiste/gridextra/tree/28f81b81c3554191e29504c313a96e6f0245aba4/R) to the last commit before I removed those functions.

**Comment by seaaan** [comment]
Thanks! You might consider updating the link of the news page to that last
commit in case others need it.
