### ISSUE TITLE
Error: nrow * ncol >= n is not TRUE

### ISSUE THREAD

**Issue by rsaporta** [baptiste/gridextra#17]
_cross post with [ggplot2 mailing list](https://groups.google.com/forum/#!topic/ggplot2/FSMwcxvSZVw)_

I'm experiencing similar issue as to what user in the ggplot2 mailing list indicates:  Old code that used to run fine now throwing error 
`Error: nrow * ncol >= n is not TRUE`

#### Original line of code - Throws Error
    arrangeGrob(P.main, nrow=1, widths=c(10), just="bottom")
    # Error: nrow * ncol >= n is not TRUE

####  Add `ncol` explicitly, throws different error
    arrangeGrob(P.main, nrow=1, ncol=5, widths=c(10), just="bottom")
    # Error: length(widths) == ncol is not TRUE

#### Change nrow from 1 to 2, and no error. But also not the output expected
    arrangeGrob(P.main, nrow=2, widths=c(10), just="bottom")
    # no error

Thanks

**Comment by baptiste** [comment]
`just` is not an argument of `arrangeGrob`, so it takes it as a grob (which it isn't), and the number of (assumed) grobs becomes incompatible with the widths.

**Comment by rsaporta** [comment]
Interesting, thank you for clarifying that.   Out of curiosity, why did it used to work in previous versions?

**Comment by baptiste** [comment]
`just` used to be a valid argument (although it wasn't clear from the function definition) that was passed to `grid.layout`. Now the layout is handled by `gtable`, which doesn't support justification (you'd have to wrap the grob in a gTree for that).

**Comment by rsaporta** [comment]
that makes sense.  Do you know off the top of your head which version I could install to use the old behavior?  (Have some old code I simply need to rerun with new data).   If not, I could go through the commits.

thanks

**Comment by baptiste** [comment]
probably [this one](https://github.com/baptiste/gridextra/tree/06b65cab23f2c1dfd8551e43f917ff2b557da222), but it may prove harder to install nowadays.

**Comment by rsaporta** [comment]
I'll give it a go, thanks again
