### ISSUE TITLE
Alpha transparency feature for tableGrob

### ISSUE THREAD

**Issue by jerodwaldman** [baptiste/gridextra#19]
I upgraded my gridExtra package from 0.9.1 to 2.0.0 and it seems to have lost the ability to use the transparency (alpha) feature for tableGrobs:

http://www.inside-r.org/packages/cran/gridExtra/docs/arrangeTableGrobs

h.odd.alpha = 1
h.even.alpha = 1
v.odd.alpha = 1
v.even.alpha = 1

I see it in the code for textGrob and rectGrob, but not tableGrob.

https://github.com/baptiste/gridextra/blob/6c1e1838dd58a246679676dc14b9ba5ac9ec3526/R/tableGrob.r

Am I missing something?

**Comment by baptiste** [comment]
The arguments have changed, aesthetic parameters are now passed in themes (nested lists). There are examples in [the vignette](https://github.com/baptiste/gridextra/wiki/tableGrob#aesthetic-formatting). However I made a few recent changes that are not yet on CRAN, so you may have to install the dev version for best results.
