### ISSUE TITLE
marrangeGrob results cannot be used in ggsave?

### ISSUE THREAD

**Issue by zhanxw** [baptiste/gridextra#21]
I used the example codes from help("marrangeGrob"), and experienced this error:

set.seed(123)
pl <- lapply(1:11, function(.x)
              qplot(1:10, rnorm(10), main=paste("plot", .x)))
ml <- marrangeGrob(pl, nrow=2, ncol=2)
ggsave("multipage.pdf", ml)

**Error in ggsave("multipage.pdf", ml) : plot should be a ggplot2 plot**

This problem only happens in v2.0, but not v0.9.1.
Is there any solution to save marrangeGrob() results?

**Comment by zhanxw** [comment]
Is this the same issue as #13 ?

**Comment by baptiste** [comment]
yes, same issue.
