### ISSUE TITLE
grid.arrange error with ggplot objects

### ISSUE THREAD

**Issue by MGNute** [baptiste/gridextra#26]
I think this should be a pretty basic function call, or at least it used to be, but something broke in grid.arrange when the arguments are strictly ggplot objects. I can't attach the data for a full minimal working example. Basically I have two ggplot objects and try to run the following command:

grid.arrange(Plot.0, Plot.1, ncol=1,main="Precision & Recall by p-distance")

And the output error message is:

Error in gList(list(grobs = list(list(x = 0.5, y = 0.5, width = 1, height = 1,  : 
  only 'grobs' allowed in "gList"
In addition: Warning message:
In grob$wrapvp <- vp : Coercing LHS to a list

It could be an issue with a different package but I ahven't been able to figure this out.

**Comment by baptiste** [comment]
use `top` instead of `main`
