### ISSUE TITLE
Consecutive arrangeGrob Plots Are Overlaid

### ISSUE THREAD

**Issue by DarioS** [baptiste/gridextra#27]
Shouldn't the PDF document have two pages, not one page with two overlaid plots ?

    library(grid)
    library(gridExtra)
    library(ggplot2)
    boxPlot <- ggplot(mtcars, aes(factor(cyl), mpg)) + geom_boxplot()
    violinPlot <- ggplot(mtcars, aes(factor(cyl), mpg)) + geom_violin()

    pdf("mileage.pdf")
    bothPlots <- arrangeGrob(boxPlot, violinPlot, nrow = 2, top = textGrob("First Title"))
    grid.draw(bothPlots)
    bothPlots <- arrangeGrob(violinPlot, boxPlot, nrow = 2, top = textGrob("Second Title"))
    grid.draw(bothPlots)
    dev.off()

If I use `grid.draw` on the boxplot and violin plot separately, I get a 2 page PDF, as desired.

    pdf("testSeparately.pdf")
    grid.draw(boxPlot)
    grid.draw(violinPlot)
    dev.off()

It seems that `arrangeGrob` is the cause of the problem.

**Comment by baptiste** [comment]
works as intended, in standard grid you're supposed to explicitly call `grid.newpage()` if you want `grid.draw()` to draw on a blank page, i.e. the default behaviour is to add things to the page, not assume that we want to erase what was there before and replace it.
ggplot2, in contrast, has always gone in the other direction. Its recently-added `grid.draw` method is just a wrapper around `print.ggplot`, which defaults to `newpage=FALSE`.
