### ISSUE TITLE
Shiny workaround doesn't work

### ISSUE THREAD

**Issue by dkulp2** [baptiste/gridextra#32]
The shiny workaround at https://github.com/baptiste/gridextra/blob/master/inst/testing/shiny.R doesn't work for me. I just get a blank page.
I added a print statement in the print.arrange function and it apparently never gets called.
Any ideas?

**Comment by baptiste** [comment]
Sorry, I don't know much about Shiny. You're probably better off asking the Rstudio team for a better solution.
