### ISSUE TITLE
[FR] ellipseGrob parameterization and output

### ISSUE THREAD

**Issue by npjc** [baptiste/gridextra#34]
Thanks for the great work.

[SVG has an ellipse element](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/ellipse) with attributes specifying the centre (`cx`, `cy`) and the radii (`rx`, `ry`).

1. It would be awesome to have the ellipseGrob parametrized the same way.
2. It would be more awesome if when you render the grob to SVG device it was actually an ellipse element.

How `grid` passes things to `grDevices` is pretty opaque to me and so sorry if I'm asking for something that is impossible here!

**Comment by baptiste** [comment]
1. what's the advantage? x, y is standard in grid graphics. I'll agree that size + aspect ratio is not necessarily the most common choice, but it's pretty trivial to make a wrapper function to convert to/from semi-axes.

2. gridExtra builds on top of grid graphics, so has no control over the device-dependent output.
