### ISSUE TITLE
Maximum number of plots for grid.arrange()

### ISSUE THREAD

**Issue by ma-lima** [baptiste/gridextra#36]
I want to show 100 plots, in a 10x10 arrangement.  
I use a loop to generate the plots and name each one (G1, G2, GP3, G4 ... G100).  

If I set up my loop for 20 iterations and use:

`grid.arrange(G1,G2,G3,G4....G20,ncol=10)`

I get what I expect: 20 plots in 2 rows with 10 columns in each row.

However, if I have more than 20 plots, I get the following message:

> Error in arrangeGrob(...) : object 'G21' not found

Is there some internal limit to grid.arrange() that restricts it to 20 objects?  
Is there a way to show more than 20 plots?

**Comment by baptiste** [comment]
there is no such restriction.

```
pl = replicate(50, ggplot(), FALSE)
grid.arrange(grobs = gl)
```
