### ISSUE TITLE
Problem with gridExtra

### ISSUE THREAD

**Issue by AswathyPaul** [baptiste/gridextra#40]
Error : object 'rbind.gtable' is not exported by 'namespace:gridExtra'

I was trying to install TCGABiolinks. I am getting this issue always. I tried to remove the gridExtra package and install it again. But then also it didn't work. I couldn't see the export(rbind.gtable) using gridExtra also. 

I will be grateful if you could help me to figure out the problem. 

Bioconductor version 3.5 (BiocInstaller 1.26.1)

**Comment by baptiste** [comment]
The function has been renamed gtable_rbind.
