### ISSUE TITLE
theme as result of ifelse

### ISSUE THREAD

**Issue by proadiga** [baptiste/gridextra#42]
Hi , 

I'm trying to add theme to tableGrob depending on `ifelse` result's (if nummber odd or even ) but i get an Error 

this my example :
```
library(gridExtra)
library(gtable)
tt1 <- ttheme_default()
tt2 <- ttheme_minimal()

tableGrob(iris[1:4, 1:2], theme=ifelse(4%% 2 == 0,tt1, tt2))
```

I got this Error 

```
 Error in data.frame(fg_params, label = as.vector(label_matrix), stringsAsFactors = FALSE) : 
  arguments imply differing number of rows: 0, 8
```
Can you please help me with this issue

Thanks,

**Comment by baptiste** [comment]
`ifelse(4%% 2 == 0,tt1, tt2)` does not return a theme like you expect.
