### ISSUE TITLE
Example on gridExtra::marrangeGrob() does not work as intended

### ISSUE THREAD

**Issue by JanvandenBrand** [baptiste/gridextra#44]
See: https://www.rdocumentation.org/packages/gridExtra/versions/0.9.1/topics/marrangeGrob

Example: 

> require(ggplot2)
> pl <- lapply(1:11, function(.x) qplot(1:10,rnorm(10), main=paste("plot",.x)))
> ml <- do.call(marrangeGrob, c(pl, list(nrow=2, ncol=2)))

Returns an error

Suggested fix:

> marrangeGrob(pl, nrow=2, ncol=2)

**Comment by baptiste** [comment]
as in 

https://www.rdocumentation.org/packages/gridExtra/versions/2.3/topics/arrangeGrob
