### ISSUE TITLE
what if(!is.unit(heights)) or if(!is.unit(widths)) in arrangeGrob() ?

### ISSUE THREAD

**Issue by WastlM** [baptiste/gridextra#7]
Previously, `heights` and `widths` were allowed to be simple numeric vectors because `arrangeGrob()` internally called `grid.layout()` which did:

    if (!is.unit(widths)) 
        widths <- unit(widths, "null")
    if (!is.unit(heights)) 
        heights <- unit(heights, "null")

I think this automatic conversion to grid units is a convenient feature and suggest to include the above code in the new version of `arrangeGrob()`. This would also break less code of packages depending on gridExtra. I could prepare a pull request if necessary.

**Comment by baptiste** [comment]
thanks for the suggestion, I've added this to arrangeGrob
